[tool.poetry]
name = "tic-tac-toe"
version = "0.1.0"
description = ""
authors = ["Juan Bernardo Benavides Rubio <jbbenavidesr@gmail.com>"]
readme = "README.md"
packages = [{include = "tic_tac_toe", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
mypy = "^0.982"
black = "^22.10.0"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
